##
##  Makefile -- Build procedure for sample mapnik_wms Apache module
##  Autogenerated via ``apxs -n mapnik_wms -g''.
##

CFLAGS=-O2 -flto=auto -ffat-lto-objects -fPIC -dPI -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -DUSE_KEY_DATABASE -I/usr/include/apache2 -I/usr/include/apr-1.0
CXXFLAGS=$(CFLAGS)

mod_mapnik_wms.so: mod_mapnik_wms.o wms.o logbuffer.o apachebuffer.o
	cc $(CFLAGS) -o mod_mapnik_wms.so -shared mod_mapnik_wms.o wms.o logbuffer.o apachebuffer.o
	strip mod_mapnik_wms.so

mod_mapnik_wms.o: mod_mapnik_wms.c
	cc $(CFLAGS) -pipe -c mod_mapnik_wms.c -o mod_mapnik_wms.o


clean: 
	rm -f mod_mapnik_wms.so mod_mapnik_wms.o wms.o logbuffer.o apachebuffer.o

install: mod_mapnik_wms.so
	install mod_mapnik_wms.so $(DESTDIR)/usr/lib/apache2/modules/
